---
deployment:
  tasks:
    - export DEPLOYPATH=/home/U1794763/public_html/
    - /bin/cp Home-page.html $DEPLOYPATH
    - /bin/cp Artikel-1.html $DEPLOYPATH
    - /bin/cp Artikel-2.html $DEPLOYPATH
    - /bin/cp Artikel-3.html $DEPLOYPATH
    - /bin/cp Program-RQM.html $DEPLOYPATH
    - /bin/cp STQ-NON-MUKIM.html $DEPLOYPATH
    - /bin/cp Tahsin&Tahfidz.html $DEPLOYPATH
    - /bin/cp Wakaf-Qur'an.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH